### ISSUE TITLE
Contents in `www/luci-static` are not provided as static resources when `luci-theme-argon` is installed on `FriendlyWrt`.

### ISSUE THREAD

**Issue by WhiskyChoy** [jerrykuku/luci-theme-argon#499]
- **System**: a varient of OpenWrt, i.e. FriendlyWrt, which is based on OpenWrt Version 21.0.2
- **Phenomenom**: icons are not shown correctly, with those resources in `www/luci-static` not available via the browser (but they exist and can be checked via SSH).

**Comment by qingtian110** [comment]
This has nothing to do with what theme style you use, because which directory will be web accessible is determined by uhttpd or nginx.

![image](https://github.com/jerrykuku/luci-theme-argon/assets/87856890/b9432791-d3f7-44ea-a649-2ee8dd11e23c)
![image](https://github.com/jerrykuku/luci-theme-argon/assets/87856890/88696285-05a4-440b-b48b-62df1dfdc6d4)

**Comment by WhiskyChoy** [comment]
After reinstall `uhttpd`, the resources now can be visited properly. Thank you!
